[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/en"
  status = 301

[[redirects]]
  from = "/en"
  to = "/en"
  status = 200

[[redirects]]
  from = "/es"
  to = "/es"
  status = 200

[[redirects]]
  from = "/fr"
  to = "/fr"
  status = 200

[[redirects]]
  from = "/de"
  to = "/de"
  status = 200

[[redirects]]
  from = "/ja"
  to = "/ja"
  status = 200

[[redirects]]
  from = "/ko"
  to = "/ko"
  status = 200

[[redirects]]
  from = "/zh"
  to = "/zh"
  status = 200

[[redirects]]
  from = "/ar"
  to = "/ar"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
